Add food detail page
meeorder/meeorder-frontend pull request #25
Opened 2023-07-31 20:03 UTC by JiMeow

2023-07-31 20:07 UTC, JiMeow commented
Good job, well done

2023-08-01 07:38 UTC, GolfGrab requested changes
fix this

2023-08-01 07:38 UTC, GolfGrab commented on src/pages/menu/[foodId].tsx
> +          />
back icon not centered on the button

2023-08-01 07:38 UTC, GolfGrab commented on src/pages/menu/[foodId].tsx
> +      </LayoutContainer>
typo AddToCardButtonNav => AddToCardButtomNav

2023-08-01 07:38 UTC, GolfGrab commented on src/pages/menu/[foodId].tsx
> +
use only in line style nor styled component not both

2023-08-01 07:38 UTC, GolfGrab commented on src/modules/user/food/components/SaveButton.tsx
> +  );
unnecessary  <> </>

2023-08-01 07:38 UTC, GolfGrab commented on src/modules/user/food/components/Content.tsx
> +      </Text>
use food description instead of hard-coded mock

2023-08-01 07:38 UTC, GolfGrab commented on src/modules/user/food/components/AddonsCard.tsx
> +  return (
this addon prop is singular use "addon" or "addOn" instead of "addons"

2023-08-01 08:08 UTC, merged