Feature/admin edit coupon form
meeorder/meeorder-frontend pull request #47
Opened 2023-09-07 08:42 UTC by JiMeow

Not connect with api yet

2023-09-07 15:11 UTC, minza55113151 commented on src/modules/admin/mock/coupon.ts
> +  numberOfReadeamedCoupons: number;
typo

2023-09-07 16:33 UTC, GolfGrab approved these changes
Nice have some Request changes

2023-09-07 16:33 UTC, GolfGrab commented on src/modules/admin/promotion/console/CouponFormSection.tsx
> +            </Form.Item>
fix input coupon images

2023-09-07 16:33 UTC, GolfGrab commented on src/modules/admin/promotion/editCoupon/CouponDeleteModal.tsx
> +    </>
remove extra <> </>

2023-09-07 16:34 UTC, GolfGrab requested changes
Request changes

2023-09-07 19:02 UTC, JiMeow commented
I resolved everything but it will in another pull request. So approve me please 😌😌.

2023-09-08 06:07 UTC, GolfGrab approved these changes

2023-09-08 06:08 UTC, merged