Feature/admin user management
meeorder/meeorder-frontend pull request #67
Opened 2023-09-27 12:05 UTC by minza55113151

PunchPunchPunch

2023-09-27 14:56 UTC, lazykern commented
👏🏿👏🏿👏🏿👏🏿

2023-09-27 15:47 UTC, GolfGrab requested changes
nice work 😘 
have one request change

2023-09-27 15:47 UTC, GolfGrab commented on src/modules/admin/setting/userManagement/components/UserList.tsx
> +
only disable action in current user row

2023-09-28 16:53 UTC, GolfGrab approved these changes
Good Job👍👍👍

2023-09-28 16:54 UTC, merged