Feature/order management
meeorder/meeorder-frontend pull request #71
Opened 2023-09-30 17:30 UTC by karnse

2023-09-30 18:17 UTC, JiMeow commented on src/pages/admin/order-management.tsx
>                // todo: filter order status by selected status
remove comment

2023-09-30 18:17 UTC, JiMeow commented on src/pages/admin/order-management.tsx
>                // allOrder.filter((order) => order.status === status)
remove comment

2023-09-30 18:18 UTC, JiMeow commented on src/modules/admin/order/components/PopOverFilter.tsx
> +  console.log("changeFilterStatusSlider", changeFilterStatusSlider);
remove log?

2023-09-30 18:18 UTC, JiMeow commented on src/modules/admin/order/components/PopOverFilter.tsx
> +    console.log("changefilterslider", changeFilterStatusSlider);
remove log?

2023-09-30 18:19 UTC, JiMeow reviewed
All hook look good, I will check components later

2023-10-01 19:20 UTC, karnse commented on src/pages/admin/order-management.tsx
>                // allOrder.filter((order) => order.status === status)
done

2023-10-01 19:20 UTC, karnse commented on src/pages/admin/order-management.tsx
>                // todo: filter order status by selected status
done

2023-10-01 19:21 UTC, karnse commented on src/modules/admin/order/components/PopOverFilter.tsx
> +  console.log("changeFilterStatusSlider", changeFilterStatusSlider);
done

2023-10-01 19:25 UTC, karnse commented on src/modules/admin/order/components/PopOverFilter.tsx
> +    console.log("changefilterslider", changeFilterStatusSlider);
done

2023-10-07 08:26 UTC, GolfGrab commented
@karnse 
pls change all action element from div to ant buttons
![image](https://github.com/meeorder/meeorder-frontend/assets/70707895/f9b80e49-1cd3-48c0-a74a-7feaa7815ed2)

2023-10-07 08:29 UTC, GolfGrab requested changes
fix button

2023-10-07 08:39 UTC, GolfGrab commented
CANCELLED reason that not related with ingredients and addon not show up 
![image](https://github.com/meeorder/meeorder-frontend/assets/70707895/fcf13a32-ac1d-4ac5-a0e3-b9d0aad41911)

![image](https://github.com/meeorder/meeorder-frontend/assets/70707895/10ebf974-c9bc-416e-bdba-0632862f399e)

2023-10-13 08:45 UTC, GolfGrab commented
@karnse let me continue this pr for you

2023-10-15 17:10 UTC, GolfGrab approved these changes
nice work

2023-10-15 17:10 UTC, merged